### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by NickGlaettli** [politanch/swissdd#14]
Using the plot_nationalvotes command, there seems to be an issue with API's.
While it has been adressed recently on Twitter, it still does not seem to work, even after reinstalling the package several times.

**Comment by ThomasWilli** [comment]
Did you install the development version? 
     
    devtools::install_github("politanch/swissdd")
    library(swissdd)

**Comment by NickGlaettli** [comment]
Yes, I used exactly the same command to reinstall the package.

**Comment by ThomasWilli** [comment]
Could you provide an error message?

**Comment by NickGlaettli** [comment]
```
> plot_nationalvotes(votedate="2020-11-29", vote_id=6360, geolevel="canton")
Votedates cannot be parsed properly. There might be an issue with the opendata.swiss-metadata API.
The download URLs cannot be parsed properly. There might be an issue with the opendata.swiss-metadata API.
Votedates cannot be parsed properly. There might be an issue with the opendata.swiss-metadata API.
The download URLs cannot be parsed properly. There might be an issue with the opendata.swiss-metadata API.
Fehler: Input must be a vector, not NULL.
Run `rlang::last_error()` to see where the error occurred.
Zusätzlich: Warnmeldungen:
1: Unknown or uninitialised column: `date`. 
2: Unknown or uninitialised column: `download_url`. 
3: Unknown or uninitialised column: `pub_date`. 
4: In max.default(numeric(0), na.rm = FALSE) :
  kein nicht-fehlendes Argument für max; gebe -Inf zurück
5: Unknown or uninitialised column: `date`. 
6: Unknown or uninitialised column: `download_url`. ``
```

**Comment by ThomasWilli** [comment]
@NickGlaettli If there are issues with the API, we try to update the development version asap. First, remove the existing package and then download the development version using `install_github`: 

    remove.packages("swissdd")
    devtools::install_github("politanch/swissdd", ref="dev")

Close and reopen `RStudio`.

    library(swissdd)

    geo_canton <- swissdd::get_geodata(geolevel = "canton")
    geo_canton$canton_id <- as.numeric(geo_canton$canton_id)

    kovi_nat <- swissdd::get_nationalvotes(votedates="2020-11-29", geolevel = "canton")%>%
      dplyr::filter(id == 6360)%>%
      dplyr::select(canton_id, jaStimmenInProzent)%>%
      mutate(canton_id=as.numeric(canton_id))

    can_df <- left_join(geo_canton, kovi_nat, by="canton_id")

    ggplot(can_df)+
      geom_sf(aes(fill=jaStimmenInProzent), color="white", size=.1)

**Comment by NickGlaettli** [comment]
Thanks, it worked!
