### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by salim-b** [politanch/swissdd#15]
Hi @tlorusso,

I've noticed that you license this package under:

https://github.com/politanch/swissdd/blob/fde2dea01135116ef452c9e16460ba1723d9a5b9/DESCRIPTION#L24

Unfortunately, this is ambigous since it doesn't clarify if it means `GPL-2.0-only` or `GPL-2.0-or-later`, but will mostly likely be interpreted as `GPL-2.0-only` which [happens to be incompatible with later versions of the license (`GPL-3-or-later`)](https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility).

I guess you didn't mean to make your code incompatible with GPL-3 code, thus I propose to change the license field in DESCRIPTION to `GPL (>= 2)`. 🙂

You can read more about the topic in [this blog post](https://www.gnu.org/licenses/identify-licenses-clearly.html).

**Comment by tlorusso** [comment]
Thanks for bringing this up @salim-b :)
