### ISSUE TITLE
get_geodata(geolevel = "zh_counting_districts")

### ISSUE THREAD

**Issue by florihas** [politanch/swissdd#16]
get_geodata(geolevel = "zh_counting_districts") returns warning message and retrieves national borders for CRAN and dev version.

Warning message:
In evalq((function (..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE,  :
  automatically selected the first layer in a data source containing more than one.

**Comment by tlorusso** [comment]
Thanks for bringing this up @florihas! We've fixed it and integrated the change into the master-branch.
